name: Validate Markdown
on:
  pull_request:
    branches: [main, dev, release/*]
  push:
    branches: [main, dev, release/*]
jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
          config_file: .markdownlint.json
